In [4]:
import numpy as np

a = np.random.randn(5)

In [5]:
print(a)

[-0.70451238  0.5361303  -1.34377666  1.65514002  0.83622406]


### It's neither a row vector nor a column vector.

In [7]:
# 열벡터도 아니고 행벡터도 아니다!
print(a.shape)

(5,)


In [8]:
print(a.T)

[-0.70451238  0.5361303  -1.34377666  1.65514002  0.83622406]


In [9]:
print(np.dot(a, a.T))

6.0282682557279434


In [10]:
a = np.random.randn(5,1)
print(a)

[[-1.10282361]
 [ 0.56860846]
 [ 1.16326191]
 [-0.03293801]
 [ 1.7976624 ]]


In [11]:
print(a.T)

[[-1.10282361  0.56860846  1.16326191 -0.03293801  1.7976624 ]]


In [13]:
print(np.dot(a,a.T))
print(np.dot(a,a.T).shape)

[[ 1.21621992e+00 -6.27074840e-01 -1.28287270e+00  3.63248203e-02
  -1.98250454e+00]
 [-6.27074840e-01  3.23315586e-01  6.61440569e-01 -1.87288339e-02
   1.02216605e+00]
 [-1.28287270e+00  6.61440569e-01  1.35317827e+00 -3.83155379e-02
   2.09115220e+00]
 [ 3.63248203e-02 -1.87288339e-02 -3.83155379e-02  1.08491281e-03
  -5.92114304e-02]
 [-1.98250454e+00  1.02216605e+00  2.09115220e+00 -5.92114304e-02
   3.23159009e+00]]
(5, 5)


In [16]:
# assert문을 사용해서 확인하자!
assert(a.shape==(5,1))